#!/bin/bash


/home/pi/YungSpaceRanger/hardware/gpsParser && /home/pi/YungSpaceRanger/hardware/recordMics 1 && python /home/pi/YungSpaceRanger/hardware/thermalCameraRead.py && sleep 2 && tar -cvzf pac.tar /home/pi/YungSpaceRanger/hardware/packet
sleep 15 && /home/pi/YungSpaceRanger/hardware/gpsParser && /home/pi/YungSpaceRanger/hardware/recordMics 1 && python /home/pi/YungSpaceRanger/hardware/thermalCameraRead.py && sleep 2 && tar -cvzf pac.tar /home/pi/YungSpaceRanger/hardware/packet
sleep 30 && /home/pi/YungSpaceRanger/hardware/gpsParser && /home/pi/YungSpaceRanger/hardware/recordMics 1 && python /home/pi/YungSpaceRanger/hardware/thermalCameraRead.py && sleep 2 && tar -cvzf pac.tar /home/pi/YungSpaceRanger/hardware/packet
sleep 45 && home/pi/YungSpaceRanger/hardware/gpsParser && /home/pi/YungSpaceRanger/hardware/recordMics 1 && python /home/pi/YungSpaceRanger/hardware/thermalCameraRead.py && sleep 2 && tar -cvzf pac.tar /home/pi/YungSpaceRanger/hardware/packet
